#!/bin/sh
/usr/bin/rpmbuild \
        --define "_binary_filedigest_algorithm 1" \
        --define "_binary_payload 1" \
        --define "__jar_repack %{nil}" \
        --define "__osgi_provides %{nil}" \
        --define "__osgi_requires %{nil}" \
        "$@"
